# Generated by Django 5.1.2 on 2024-11-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('year', models.IntegerField(max_length=4)),
                ('price', models.IntegerField(max_length=10)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
